### PR TITLE
#119 lock of mutex

### PR DESCRIPTION
**Pull request by Kenny50**
In #119 describe permanent lock of mutex when condition throw error

what is new
- add two test modify `updateTokenHandler` and `isCredentialsActual`, both will throw error at first time, then success at second time
    - In previous version the mutex will lock permanently
- using `withLock` automatically lock and unlock

### CODE REVIEW

**Comment by Kenny50** [comment]
Consider add withTimeOut, so when we run test it could finish and tell us where is the problem, instead of wait for a locked mutex until we cancel the test manually

```kotlin
val result = runBlocking {
    withTimeout(30000){
        client.get("localhost")
    }
}
```

**Comment by Kenny50** [comment]
I choose force push because ` PR run failed: KMP library compilation check `, with error message `NoBlankLineBeforeRbrace - [] at /Users/runner/work/moko-network/moko-network/network/src/commonMain/kotlin/dev/icerock/moko/network/plugins/RefreshTokenPlugin.kt:76:1`

Since I only have to remove an empty line, from this
```kotlin
    }

}
```
to this
```kotlin
    }
}
```
I decide to force push instead of make an extra commit.

**Comment by Kenny50** [comment]
@Alex009 Would you might check it out?

**Comment by epicarchitect** [comment]
@Alex009, reviewed

**Review by Alex009 — APPROVED** [review]

**Pull request merged**
