### PR TITLE
Allow to enable public API explicitly

### PR DESCRIPTION
**Pull request by xsveda**
This PR adds `apiVisibility` attribute as a direct replacement for `isInternal` that allows to explicitly specify generated classes visibility as `public`. Useful when Kotlin Explicit API mode is used: https://kotlinlang.org/docs/reference/whatsnew14.html#explicit-api-mode-for-library-authors

### CODE REVIEW

**Comment by xsveda** [comment]
The build is failing due to `public` visibility modifier being applied, even though `publicApi` property is defined as `false`.

Even if I hardcode the values in `MultiPlatformNetworkGeneratorPlugin`, the `public` modifier is still applied.
```
                    additionalProperties.set(
                        mutableMapOf(
                            "publicApi" to "false",
                            "nonPublicApi" to "false",
                            "openApiClasses" to "false"
                        )
                    )
```
Is there something need to be done to make `publicApi` property work?

**Comment by xsveda** [comment]
Seems like the `openApiClasses` flag is also not working. `additionalProperties` is of type `Map<String, String>` and when we put `"true"` it won't handle that as boolean value.

**Comment by xsveda** [comment]
Confirmed, when I've updated OpenApi Tools Gradle plugin to accept also nonString properties both `publicApi` and `openApiClasses` works just fine. Will do PR for OpenApi project soon. This PR is actually OK, just need the OpenAPI gradle plugin update first

**Comment by xsveda** [comment]
Tracked under https://github.com/icerockdev/moko-network/issues/59

**Comment by Alex009** [comment]
this fixed by preprocessing inside KtorGenerator. and if `isInternal = false` we generate now `public` classes explicit

**Pull request closed without merging**
